import os
import re
from pathlib import Path

# ---------------------------------------------------------------------------
# LLM — any OpenAI-compatible Chat Completions endpoint (hosted provider,
# gateway, or a local Ollama at http://localhost:11434/v1). Chat is disabled
# until both LLM_BASE_URL and LLM_MODEL are set.
# ---------------------------------------------------------------------------
LLM_BASE_URL = os.environ.get("LLM_BASE_URL", "").rstrip("/")
LLM_API_KEY = os.environ.get("LLM_API_KEY", "")
LLM_MODEL = os.environ.get("LLM_MODEL", "")
LLM_TIMEOUT_SECONDS = float(os.environ.get("LLM_TIMEOUT_SECONDS", "30"))
LLM_MAX_TOKENS = int(os.environ.get("LLM_MAX_TOKENS", "400"))

# ---------------------------------------------------------------------------
# CORS
# ---------------------------------------------------------------------------
ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        "ALLOWED_ORIGINS", "http://localhost:8080,http://127.0.0.1:8080"
    ).split(",")
    if origin.strip()
]

# ---------------------------------------------------------------------------
# Client IP
# ---------------------------------------------------------------------------
# Header set by the hosting platform's edge that carries the real client IP
# and cannot be forged by the client (e.g. "cf-connecting-ip" on Cloudflare,
# "x-real-ip" on Vercel). Empty = use the TCP peer address; never trust a
# client-supplied X-Forwarded-For.
CLIENT_IP_HEADER = os.environ.get("CLIENT_IP_HEADER", "").strip().lower()

# ---------------------------------------------------------------------------
# SMTP / Email
# ---------------------------------------------------------------------------
SMTP_SERVER = os.environ.get("SMTP_SERVER", "smtp.gmail.com")
SMTP_PORT = int(os.environ.get("SMTP_PORT", "587"))
SMTP_USER = os.environ.get("SMTP_USER", "")
SMTP_PASSWORD = os.environ.get("SMTP_PASSWORD", "")
CONTACT_RECEIVER_EMAIL = os.environ.get("CONTACT_RECEIVER_EMAIL", "")
# Log contact messages instead of sending them (local development only).
MAIL_DRY_RUN = os.environ.get("MAIL_DRY_RUN", "").lower() in ("1", "true", "yes")

# ---------------------------------------------------------------------------
# Data
# ---------------------------------------------------------------------------
# Generated by `npm run sync` from content/. Overridable because serverless
# bundlers may place the file somewhere else.
CV_DATA_PATH = Path(
    os.environ.get(
        "CV_DATA_PATH",
        Path(__file__).resolve().parent.parent.parent / "data" / "cv_data.json",
    )
)

# ---------------------------------------------------------------------------
# Chat limits
# ---------------------------------------------------------------------------
MAX_HISTORY_MESSAGES = 20
MAX_MESSAGE_LENGTH = 2000

# How many recent turns to fold into the topic-relevance check, so short
# follow-ups like "tell me more" inherit the relevance of the prior turn.
RELEVANCE_CONTEXT_TURNS = 2

# ---------------------------------------------------------------------------
# Rate limiting (in-memory, per instance)
# ---------------------------------------------------------------------------
RATE_LIMIT_MAX_REQUESTS = 20
RATE_LIMIT_WINDOW_SECONDS = 600  # 10 minutes

CONTACT_RATE_LIMIT_MAX = 5
CONTACT_RATE_LIMIT_WINDOW = 600  # 10 minutes

# Upper bound on tracked IPs per limiter, so spoofed/unique IPs cannot grow
# memory without limit.
RATE_LIMIT_MAX_TRACKED_KEYS = 10_000

# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------
EMAIL_REGEX = re.compile(r"^[^@\s]+@[^@\s]+\.[^@\s]+$")
